### ISSUE TITLE
Running the React example problem

### ISSUE THREAD

**Issue by onuraltas** [yuzhenmi/taleweaver#109]
I'm trying to run React example. I tried the following steps. But I wasn't able to run the example. 

# In packages/core
npm install  # Install dev dependencies
npm run dev  # Build in watch mode

# In examples/taleweaver-example-react
npm install  # Install dependencies
npm start  # Start dev server (create-react-app)

I had this error;

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

▼ 2 stack frames were expanded.
resolveDispatcher
C:/devel/taleweaver-dependabot-npm_and_yarn-packages-core-lodash-4.17.19/packages/react/node_modules/react/cjs/react.development.js:1465
useState
C:/devel/taleweaver-dependabot-npm_and_yarn-packages-core-lodash-4.17.19/packages/react/node_modules/react/cjs/react.development.js:1496
▲ 2 stack frames were expanded.
TaleweaverProvider
C:/devel/taleweaver-dependabot-npm_and_yarn-packages-core-lodash-4.17.19/packages/react/dist/context.js:18
  15 | }
  16 | export var TaleweaverProvider = function (_a) {
  17 |     var children = _a.children;
> 18 |     var _b = useState(null), taleweaver = _b[0], setTaleweaver = _b[1];
  19 |     var _c = useState(null), font = _c[0], setFont = _c[1];
  20 |     var refreshFront = useCallback(function () {
  21 |         if (!taleweaver) {

**Comment by sunjingwu** [comment]
You also need run 
```
npm install # Install dev dependencies
npm run dev # Build in watch mode
```
in packages/react


Two React instance problem reference:
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by onuraltas** [comment]
Thanks. I resolved the issue with npm link command. Keep up the good work. Regards
