### ISSUE TITLE
Loading a document from file

### ISSUE THREAD

**Issue by onuraltas** [yuzhenmi/taleweaver#110]
Hi,

I'm trying to open a document from file after initialDoc opened. What is the right way to do it? I'm planning to call modelService or commandService. I couldn't figure it out yet. 

Best regards

**Comment by yuzhenmi** [comment]
This project is still WIP, but I would say it is best in this case to initialize the editor after you have your document data. The editor would have to maintain history tracking, so if you're loading a document fresh, it should be loaded in a fresh editor instance.

If you already have an editor open and would like to load another document in that condition, then the original editor instance should be destroyed and a new one created.

**Comment by onuraltas** [comment]
I modified App.tsx in the example project. Thank you.
