### ISSUE TITLE
Text formatting options

### ISSUE THREAD

**Issue by yuzhenmi** [yuzhenmi/taleweaver#6]
Word processors are expected to have font styling options, such as:
- Bold
- Italic
- Strikethrough
- Font size
- Font family
- Color
- Background color

We should support them.

**Comment by tobischw** [comment]
Does this work in its current state? Using the demo at https://yuzhenmi.github.io/taleweaver/, I am unable to bold, underline, change font size, etc...

**Comment by yuzhenmi** [comment]
No, it does not, this is still being developed. Currently, it just reads the formatting and displays them on the toolbar but you cannot change them.

**Comment by yuzhenmi** [comment]
The current design I have in mind for implementing styling:
* Each node in the render tree carries a an arbitrary style object, the style object is expected to be built from model attributes plus defaults
* Style gets propagated from the render tree all the way to the view tree for rendering to the DOM
* When querying styles for a given selection range, styles are returned as hashmap of component/part to array of style object, for example, if there are two text segments with different styles, those style objects will appear under the text component/part key as an array of 2 style objects:
```
interface IStyles {
    [componentId: string]: {
        [partId: string]: Array<{
            [key: string]: any;
        }>;
    };
}
```
* When applying styles, styles are applied to the deepest nodes in the tree if multiple instances of the same component/part type wrap each other

I think this works fine for the current supported models, but won't work when tables are introduced. Need more investigation into this.

**Comment by yuzhenmi** [comment]
I plan to introduce 2 command handlers for applying formatting:
1. Given component ID, part ID, and partial attributes, apply partial attributes on the deepest instances of the model nodes that match the given component/part IDs. This is useful for applying style on whole nodes.
2. Given component ID, part ID, and partial attributes, apply partial attributes on the deepest instances of the model nodes that match the given component/part IDs, and split out the selected range if necessary to ensure that the boundaries of the range are node boundaries. This is useful for applying style on selected ranges.
