### ISSUE TITLE
TypeScript loader missing?

### ISSUE THREAD

**Issue by jkhaui** [yuzhenmi/taleweaver#69]
Hey,

Your work so far on pagination looks amazing. I'm trying to replicate your example, but after installing npm packages I get this error:
![image](https://user-images.githubusercontent.com/36477474/62992328-5dd32000-be96-11e9-9fad-f170fe62c6fa.png)

I just ran npm install in the Taleweaver create-react-app example, is there something else I should be doing? Thanks!

P.s. I came across your lib from Reddit. It's a shame there hasn't been more interest. There are a number of people using other editors, such as slate.js, who are also attempting the pagination issue but I think you are furthest along. 
If there's any way I can contribute, I'd love to. The only thing is I've started building off draft.js and have features such as footnotes implemented, so I'm hesitant to relearn and rebuild everything from scratch. I wonder if there's some way to integrate your pagination feature within existing RTE frameworks... 🤔

**Comment by tobischw** [comment]
I believe you first must build the module at `packages/core` using `npm run build` and then run `npm install` in the examples folder.

I could be wrong, the error message makes me think that TypeScript can't be found.

**Comment by jkhaui** [comment]
Thanks @tobischw , you're probably right I'll try the build command instead!
